[tox]  
requires =
    tox>=4
env_list =
    py{312,313,314}-dj{52,60}

[testenv]  
runner = uv-venv-lock-runner
description = Run the tests with pytest
deps =
    pytest-django
    dj52: Django>=5.2,<6
    dj60: Django>=6,<6.2
setenv =
    PYTHONWARNINGS=all
commands =
    pytest -v
