name: Run unit tests

on: [push, pull_request]

jobs:
  run_tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        id: checkout-repo
        with:
          fetch-depth: 0
      - name: Install uv build tool
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install packages
        run: uv tool install tox --with tox-uv
      - name: Tox tests
        run: tox -v
